/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fatfind (void)
{
  GtkWidget *fatfind;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *open1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *about1;
  GtkWidget *image14;
  GtkWidget *hbox1;
  GtkWidget *vbox3;
  GtkWidget *table1;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *combobox1;
  GtkWidget *hbox3;
  GtkWidget *sourcePath;
  GtkWidget *vbox5;
  GtkWidget *table2;
  GtkWidget *minRadius;
  GtkWidget *maxRadius;
  GtkWidget *numCircles;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *gaussianBlur;
  GtkWidget *label14;
  GtkWidget *hbox6;
  GtkWidget *setMinButton;
  GtkWidget *alignment3;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label7;
  GtkWidget *resetButton;
  GtkWidget *alignment5;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label9;
  GtkWidget *setMaxButton;
  GtkWidget *alignment4;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label8;
  GtkWidget *vbox7;
  GtkWidget *notebook1;
  GtkWidget *gammacurve1;
  GtkWidget *label10;
  GtkWidget *expander1;
  GtkWidget *scrolledwindow4;
  GtkWidget *textview2;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *vbox8;
  GtkWidget *label20;
  GtkWidget *hseparator2;
  GtkWidget *progressBar;
  GtkWidget *startButton;
  GtkWidget *alignment8;
  GtkWidget *hbox11;
  GtkWidget *image21;
  GtkWidget *label19;
  GtkWidget *vseparator2;
  GtkWidget *vbox4;
  GtkWidget *vbox6;
  GtkWidget *thumb1;
  GtkWidget *thumbButton1;
  GtkWidget *alignment9;
  GtkWidget *hbox12;
  GtkWidget *image22;
  GtkWidget *label21;
  GtkWidget *hseparator8;
  GtkWidget *thumb2;
  GtkWidget *thumbButton2;
  GtkWidget *alignment10;
  GtkWidget *hbox13;
  GtkWidget *image23;
  GtkWidget *label22;
  GtkWidget *hseparator9;
  GtkWidget *thumb3;
  GtkWidget *thumbButton3;
  GtkWidget *alignment11;
  GtkWidget *hbox14;
  GtkWidget *image24;
  GtkWidget *label23;
  GtkWidget *hseparator10;
  GtkWidget *hbox5;
  GtkWidget *backButton;
  GtkWidget *alignment13;
  GtkWidget *hbox16;
  GtkWidget *image26;
  GtkWidget *label25;
  GtkWidget *label3;
  GtkWidget *nextButton;
  GtkWidget *alignment12;
  GtkWidget *hbox15;
  GtkWidget *image25;
  GtkWidget *label24;
  GtkWidget *hseparator7;
  GtkWidget *vbox9;
  GtkWidget *combobox2;
  GtkWidget *sortButton;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label1;
  GtkWidget *vseparator1;
  GtkWidget *vbox2;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GSList *radiotoolbutton1_group = NULL;
  GtkWidget *tmp_image;
  GtkWidget *radiotoolbutton1;
  GtkWidget *radiotoolbutton2;
  GtkWidget *radiotoolbutton3;
  GtkWidget *radiotoolbutton4;
  GtkWidget *radiotoolbutton5;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *largeImage;
  GtkWidget *hseparator6;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport2;
  GtkWidget *frame1;
  GtkWidget *alignment7;
  GtkWidget *imageInfo;
  GtkWidget *label16;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fatfind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fatfind), _("FatFind v1.4b"));
  gtk_window_set_destroy_with_parent (GTK_WINDOW (fatfind), TRUE);
  gtk_window_set_icon_name (GTK_WINDOW (fatfind), "gtk-zoom-in");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (fatfind), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), open1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  about1 = gtk_image_menu_item_new_with_mnemonic (_("_About FatFind"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about1);

  image14 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image14);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image14);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox3, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 5);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox3), table1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Local:"));
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table1), checkbutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton1), TRUE);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Diamond: "));
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table1), checkbutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_table_attach (GTK_TABLE (table1), combobox1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Default Album"));

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_table_attach (GTK_TABLE (table1), hbox3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  sourcePath = gtk_entry_new ();
  gtk_widget_show (sourcePath);
  gtk_box_pack_start (GTK_BOX (hbox3), sourcePath, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (sourcePath), _("/diamonddata"));
  gtk_entry_set_invisible_char (GTK_ENTRY (sourcePath), 9679);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox5, TRUE, TRUE, 0);

  table2 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox5), table2, FALSE, TRUE, 0);

  minRadius = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0.5, 0, 1, 0.1, 0, 0)));
  gtk_widget_show (minRadius);
  gtk_table_attach (GTK_TABLE (table2), minRadius, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  maxRadius = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (3, 1, 10, 0.1, 0, 0)));
  gtk_widget_show (maxRadius);
  gtk_table_attach (GTK_TABLE (table2), maxRadius, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  numCircles = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (20, 1, 100, 1, 0, 0)));
  gtk_widget_show (numCircles);
  gtk_table_attach (GTK_TABLE (table2), numCircles, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label4 = gtk_label_new (_("Min Radius:"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table2), label4, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_("Max Radius:"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new (_("Num. Circles:"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  gaussianBlur = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 10, 0.1, 0, 0)));
  gtk_widget_show (gaussianBlur);
  gtk_table_attach (GTK_TABLE (table2), gaussianBlur, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label14 = gtk_label_new (_("Gaussian:"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  hbox6 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox6, FALSE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (hbox6), 5);

  setMinButton = gtk_button_new ();
  gtk_widget_show (setMinButton);
  gtk_box_pack_start (GTK_BOX (hbox6), setMinButton, FALSE, FALSE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (setMinButton), alignment3);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Set Min"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  resetButton = gtk_button_new ();
  gtk_widget_show (resetButton);
  gtk_box_pack_start (GTK_BOX (hbox6), resetButton, FALSE, FALSE, 0);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (resetButton), alignment5);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Reset"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);

  setMaxButton = gtk_button_new ();
  gtk_widget_show (setMaxButton);
  gtk_box_pack_start (GTK_BOX (hbox6), setMaxButton, FALSE, FALSE, 0);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (setMaxButton), alignment4);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Set Max"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox5), vbox7, TRUE, TRUE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox7), notebook1, FALSE, TRUE, 0);
  gtk_widget_set_size_request (notebook1, -1, 200);

  gammacurve1 = gtk_gamma_curve_new ();
  gtk_widget_show (gammacurve1);
  gtk_container_add (GTK_CONTAINER (notebook1), gammacurve1);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), gammacurve1,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_curve_set_range (GTK_CURVE (GTK_GAMMA_CURVE (gammacurve1)->curve), 0, 1, 0, 1);

  label10 = gtk_label_new (_("Radius Distribution"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label10);

  expander1 = gtk_expander_new (NULL);
  gtk_widget_show (expander1);
  gtk_container_add (GTK_CONTAINER (notebook1), expander1);
  gtk_expander_set_expanded (GTK_EXPANDER (expander1), TRUE);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (expander1), scrolledwindow4);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), textview2);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview2)), _("IP: 127.0.0.1\nGIDIDX: 00:00:00:00:00:00:00:01\n\nDATAROOT /diamonddata\nCACHEDIR /diamondcache\nINDEXDIR /diamondindex\nDATATYPE native"), -1);

  label13 = gtk_label_new (_("localhost"));
  gtk_widget_show (label13);
  gtk_expander_set_label_widget (GTK_EXPANDER (expander1), label13);

  label12 = gtk_label_new (_("Server Info"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label12);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (vbox7), vbox8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 10);

  label20 = gtk_label_new ("");
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (vbox8), label20, TRUE, TRUE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator2, FALSE, TRUE, 0);

  progressBar = gtk_progress_bar_new ();
  gtk_widget_show (progressBar);
  gtk_box_pack_start (GTK_BOX (vbox3), progressBar, FALSE, FALSE, 5);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progressBar), _("Exploration Progress"));

  startButton = gtk_button_new ();
  gtk_widget_show (startButton);
  gtk_box_pack_start (GTK_BOX (vbox3), startButton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (startButton, -1, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (startButton), alignment8);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox11);

  image21 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox11), image21, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Start Exploration"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox11), label19, FALSE, FALSE, 0);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_box_pack_start (GTK_BOX (hbox1), vseparator2, FALSE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox4, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 5);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox6, TRUE, TRUE, 0);

  thumb1 = create_pixmap (fatfind, NULL);
  gtk_widget_show (thumb1);
  gtk_box_pack_start (GTK_BOX (vbox6), thumb1, TRUE, TRUE, 0);

  thumbButton1 = gtk_button_new ();
  gtk_widget_show (thumbButton1);
  gtk_box_pack_start (GTK_BOX (vbox6), thumbButton1, FALSE, FALSE, 0);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (thumbButton1), alignment9);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox12);

  image22 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox12), image22, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("View"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox12), label21, FALSE, FALSE, 0);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator8, FALSE, FALSE, 5);

  thumb2 = create_pixmap (fatfind, NULL);
  gtk_widget_show (thumb2);
  gtk_box_pack_start (GTK_BOX (vbox6), thumb2, TRUE, TRUE, 0);

  thumbButton2 = gtk_button_new ();
  gtk_widget_show (thumbButton2);
  gtk_box_pack_start (GTK_BOX (vbox6), thumbButton2, FALSE, FALSE, 0);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (thumbButton2), alignment10);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox13);

  image23 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox13), image23, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("View"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox13), label22, FALSE, FALSE, 0);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_show (hseparator9);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator9, FALSE, TRUE, 5);

  thumb3 = create_pixmap (fatfind, NULL);
  gtk_widget_show (thumb3);
  gtk_box_pack_start (GTK_BOX (vbox6), thumb3, TRUE, TRUE, 0);

  thumbButton3 = gtk_button_new ();
  gtk_widget_show (thumbButton3);
  gtk_box_pack_start (GTK_BOX (vbox6), thumbButton3, FALSE, FALSE, 0);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (thumbButton3), alignment11);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox14);

  image24 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox14), image24, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("View"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox14), label23, FALSE, FALSE, 0);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_show (hseparator10);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator10, FALSE, TRUE, 5);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox5, FALSE, FALSE, 5);

  backButton = gtk_button_new ();
  gtk_widget_show (backButton);
  gtk_box_pack_start (GTK_BOX (hbox5), backButton, FALSE, FALSE, 0);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (backButton), alignment13);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox16);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox16), image26, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic ("Back 3");
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox16), label25, FALSE, FALSE, 0);

  label3 = gtk_label_new (_(" "));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox5), label3, TRUE, TRUE, 0);

  nextButton = gtk_button_new ();
  gtk_widget_show (nextButton);
  gtk_box_pack_start (GTK_BOX (hbox5), nextButton, FALSE, FALSE, 0);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (nextButton), alignment12);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox15);

  image25 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox15), image25, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic ("Next 3");
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox15), label24, FALSE, FALSE, 0);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator7, FALSE, FALSE, 5);
  gtk_widget_set_size_request (hseparator7, 200, -1);

  vbox9 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox9, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_box_pack_start (GTK_BOX (vbox9), combobox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (combobox2), 2);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Sort By:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Number of Circles"));

  sortButton = gtk_button_new ();
  gtk_widget_show (sortButton);
  gtk_box_pack_start (GTK_BOX (vbox9), sortButton, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (sortButton), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Sort Results"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox2), label1, FALSE, FALSE, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox1), vseparator1, FALSE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, TRUE, TRUE, 5);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox2), toolbar1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 5);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  radiotoolbutton1 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton1), _("Original"));
  tmp_image = gtk_image_new_from_stock ("gtk-select-color", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton1), tmp_image);
  gtk_widget_show (radiotoolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiotoolbutton1);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton1), radiotoolbutton1_group);
  radiotoolbutton1_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton1));

  radiotoolbutton2 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton2), _("Edges"));
  tmp_image = gtk_image_new_from_stock ("gtk-connect", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton2), tmp_image);
  gtk_widget_show (radiotoolbutton2);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiotoolbutton2);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton2), radiotoolbutton1_group);
  radiotoolbutton1_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton2));

  radiotoolbutton3 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton3), _("Hough"));
  tmp_image = gtk_image_new_from_stock ("gtk-convert", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton3), tmp_image);
  gtk_widget_show (radiotoolbutton3);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiotoolbutton3);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton3), radiotoolbutton1_group);
  radiotoolbutton1_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton3));

  radiotoolbutton4 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton4), _("Gaussian"));
  tmp_image = gtk_image_new_from_stock ("gtk-floppy", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton4), tmp_image);
  gtk_widget_show (radiotoolbutton4);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiotoolbutton4);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton4), radiotoolbutton1_group);
  radiotoolbutton1_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton4));

  radiotoolbutton5 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton5), _("Circles"));
  tmp_image = gtk_image_new_from_stock ("gtk-cdrom", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton5), tmp_image);
  gtk_widget_show (radiotoolbutton5);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiotoolbutton5);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton5), radiotoolbutton1_group);
  radiotoolbutton1_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton5));

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 5);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  largeImage = create_pixmap (fatfind, NULL);
  gtk_widget_show (largeImage);
  gtk_container_add (GTK_CONTAINER (viewport1), largeImage);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator6, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator6, 500, -1);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow3, FALSE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow3), 5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_NEVER);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport2);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (viewport2), frame1);
  gtk_widget_set_size_request (frame1, -1, 125);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (frame1), alignment7);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 12, 0);

  imageInfo = gtk_label_new ("");
  gtk_widget_show (imageInfo);
  gtk_container_add (GTK_CONTAINER (alignment7), imageInfo);

  label16 = gtk_label_new (_("Selected Image Info:"));
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  g_signal_connect ((gpointer) fatfind, "destroy",
                    G_CALLBACK (on_fatfind_destroy),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) startButton, "clicked",
                    G_CALLBACK (on_startButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) thumbButton1, "clicked",
                    G_CALLBACK (on_thumbButton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) thumbButton2, "clicked",
                    G_CALLBACK (on_thumbButton2_clicked),
                    NULL);
  g_signal_connect ((gpointer) thumbButton3, "clicked",
                    G_CALLBACK (on_thumbButton3_clicked),
                    NULL);
  g_signal_connect ((gpointer) sortButton, "clicked",
                    G_CALLBACK (on_sortButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton1, "toggled",
                    G_CALLBACK (on_radiotoolbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton2, "toggled",
                    G_CALLBACK (on_radiotoolbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton3, "toggled",
                    G_CALLBACK (on_radiotoolbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton4, "toggled",
                    G_CALLBACK (on_radiotoolbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton5, "toggled",
                    G_CALLBACK (on_radiotoolbutton5_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fatfind, fatfind, "fatfind");
  GLADE_HOOKUP_OBJECT (fatfind, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (fatfind, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (fatfind, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (fatfind, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (fatfind, open1, "open1");
  GLADE_HOOKUP_OBJECT (fatfind, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (fatfind, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (fatfind, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (fatfind, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (fatfind, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (fatfind, about1, "about1");
  GLADE_HOOKUP_OBJECT (fatfind, image14, "image14");
  GLADE_HOOKUP_OBJECT (fatfind, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fatfind, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (fatfind, table1, "table1");
  GLADE_HOOKUP_OBJECT (fatfind, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (fatfind, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (fatfind, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (fatfind, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fatfind, sourcePath, "sourcePath");
  GLADE_HOOKUP_OBJECT (fatfind, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (fatfind, table2, "table2");
  GLADE_HOOKUP_OBJECT (fatfind, minRadius, "minRadius");
  GLADE_HOOKUP_OBJECT (fatfind, maxRadius, "maxRadius");
  GLADE_HOOKUP_OBJECT (fatfind, numCircles, "numCircles");
  GLADE_HOOKUP_OBJECT (fatfind, label4, "label4");
  GLADE_HOOKUP_OBJECT (fatfind, label5, "label5");
  GLADE_HOOKUP_OBJECT (fatfind, label6, "label6");
  GLADE_HOOKUP_OBJECT (fatfind, gaussianBlur, "gaussianBlur");
  GLADE_HOOKUP_OBJECT (fatfind, label14, "label14");
  GLADE_HOOKUP_OBJECT (fatfind, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (fatfind, setMinButton, "setMinButton");
  GLADE_HOOKUP_OBJECT (fatfind, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fatfind, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (fatfind, image11, "image11");
  GLADE_HOOKUP_OBJECT (fatfind, label7, "label7");
  GLADE_HOOKUP_OBJECT (fatfind, resetButton, "resetButton");
  GLADE_HOOKUP_OBJECT (fatfind, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (fatfind, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (fatfind, image13, "image13");
  GLADE_HOOKUP_OBJECT (fatfind, label9, "label9");
  GLADE_HOOKUP_OBJECT (fatfind, setMaxButton, "setMaxButton");
  GLADE_HOOKUP_OBJECT (fatfind, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fatfind, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (fatfind, image12, "image12");
  GLADE_HOOKUP_OBJECT (fatfind, label8, "label8");
  GLADE_HOOKUP_OBJECT (fatfind, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (fatfind, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (fatfind, gammacurve1, "gammacurve1");
  GLADE_HOOKUP_OBJECT (fatfind, label10, "label10");
  GLADE_HOOKUP_OBJECT (fatfind, expander1, "expander1");
  GLADE_HOOKUP_OBJECT (fatfind, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (fatfind, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (fatfind, label13, "label13");
  GLADE_HOOKUP_OBJECT (fatfind, label12, "label12");
  GLADE_HOOKUP_OBJECT (fatfind, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (fatfind, label20, "label20");
  GLADE_HOOKUP_OBJECT (fatfind, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (fatfind, progressBar, "progressBar");
  GLADE_HOOKUP_OBJECT (fatfind, startButton, "startButton");
  GLADE_HOOKUP_OBJECT (fatfind, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (fatfind, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (fatfind, image21, "image21");
  GLADE_HOOKUP_OBJECT (fatfind, label19, "label19");
  GLADE_HOOKUP_OBJECT (fatfind, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (fatfind, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (fatfind, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (fatfind, thumb1, "thumb1");
  GLADE_HOOKUP_OBJECT (fatfind, thumbButton1, "thumbButton1");
  GLADE_HOOKUP_OBJECT (fatfind, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (fatfind, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (fatfind, image22, "image22");
  GLADE_HOOKUP_OBJECT (fatfind, label21, "label21");
  GLADE_HOOKUP_OBJECT (fatfind, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (fatfind, thumb2, "thumb2");
  GLADE_HOOKUP_OBJECT (fatfind, thumbButton2, "thumbButton2");
  GLADE_HOOKUP_OBJECT (fatfind, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (fatfind, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (fatfind, image23, "image23");
  GLADE_HOOKUP_OBJECT (fatfind, label22, "label22");
  GLADE_HOOKUP_OBJECT (fatfind, hseparator9, "hseparator9");
  GLADE_HOOKUP_OBJECT (fatfind, thumb3, "thumb3");
  GLADE_HOOKUP_OBJECT (fatfind, thumbButton3, "thumbButton3");
  GLADE_HOOKUP_OBJECT (fatfind, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (fatfind, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (fatfind, image24, "image24");
  GLADE_HOOKUP_OBJECT (fatfind, label23, "label23");
  GLADE_HOOKUP_OBJECT (fatfind, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (fatfind, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (fatfind, backButton, "backButton");
  GLADE_HOOKUP_OBJECT (fatfind, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (fatfind, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (fatfind, image26, "image26");
  GLADE_HOOKUP_OBJECT (fatfind, label25, "label25");
  GLADE_HOOKUP_OBJECT (fatfind, label3, "label3");
  GLADE_HOOKUP_OBJECT (fatfind, nextButton, "nextButton");
  GLADE_HOOKUP_OBJECT (fatfind, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (fatfind, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (fatfind, image25, "image25");
  GLADE_HOOKUP_OBJECT (fatfind, label24, "label24");
  GLADE_HOOKUP_OBJECT (fatfind, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (fatfind, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (fatfind, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (fatfind, sortButton, "sortButton");
  GLADE_HOOKUP_OBJECT (fatfind, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fatfind, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fatfind, image3, "image3");
  GLADE_HOOKUP_OBJECT (fatfind, label1, "label1");
  GLADE_HOOKUP_OBJECT (fatfind, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (fatfind, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (fatfind, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (fatfind, radiotoolbutton1, "radiotoolbutton1");
  GLADE_HOOKUP_OBJECT (fatfind, radiotoolbutton2, "radiotoolbutton2");
  GLADE_HOOKUP_OBJECT (fatfind, radiotoolbutton3, "radiotoolbutton3");
  GLADE_HOOKUP_OBJECT (fatfind, radiotoolbutton4, "radiotoolbutton4");
  GLADE_HOOKUP_OBJECT (fatfind, radiotoolbutton5, "radiotoolbutton5");
  GLADE_HOOKUP_OBJECT (fatfind, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (fatfind, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (fatfind, largeImage, "largeImage");
  GLADE_HOOKUP_OBJECT (fatfind, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (fatfind, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (fatfind, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (fatfind, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (fatfind, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (fatfind, imageInfo, "imageInfo");
  GLADE_HOOKUP_OBJECT (fatfind, label16, "label16");

  gtk_widget_grab_default (combobox1);
  gtk_window_add_accel_group (GTK_WINDOW (fatfind), accel_group);

  return fatfind;
}

