/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <glade/glade.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

#include "fatfind.h"

static struct collection_t collections[MAX_ALBUMS+1] = { { NULL } };
gid_list_t diamond_gid_list;
ls_search_handle_t diamond_handle;

static void init_diamond(void) {
  int i;
  int j;

  printf("reading collections...\n");
  {
    void *cookie;
    char *name;
    int err;
    int pos = 0;
    err = nlkup_first_entry(&name, &cookie);
    while(!err && pos < MAX_ALBUMS)
      {
	collections[pos].name = name;
	collections[pos].active = pos ? 0 : 1; /* first one active */
	pos++;
	err = nlkup_next_entry(&name, &cookie);
      }
    collections[pos].name = NULL;
  }


  printf("reading gid_map...\n");
  for (i=0; i<MAX_ALBUMS && collections[i].name; i++) {
    if (collections[i].active) {
      int err;
      int num_gids = MAX_ALBUMS;
      groupid_t gids[MAX_ALBUMS];
      err = nlkup_lookup_collection(collections[i].name, &num_gids, gids);
      g_assert(!err);
      for (j=0; j < num_gids; j++) {
	diamond_gid_list.gids[diamond_gid_list.num_gids++] = gids[j];
      }
    }
  }

  diamond_handle = ls_init_search();
  ls_set_searchlist(diamond_handle, 1, &diamond_gid_list);

  // XXX
  /*
  ls_start_search(diamond_handle);
  while(1) {
    ls_obj_handle_t obj;
    void *data;
    int len;
    ls_next_object(diamond_handle, &obj, 0);
    lf_read_attr(obj, "Display-Name", &len, &data);
    printf("item: %s\n", data);
  }
  */
}


static void setup_saved_search_store(void) {
  GtkTreeView *v = GTK_TREE_VIEW(glade_xml_get_widget(g_xml,
						      "definedSearches"));
  GtkCellRenderer *renderer;
  GtkTreeViewColumn *column;

  saved_search_store = gtk_list_store_new(3,
					  G_TYPE_STRING,
					  G_TYPE_DOUBLE,
					  G_TYPE_DOUBLE);

  gtk_tree_view_set_model(v, GTK_TREE_MODEL(saved_search_store));


  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes ("Name",
						     renderer,
						     "text", 0,
						     NULL);
  gtk_tree_view_append_column (GTK_TREE_VIEW (v), column);
}

static void setup_thumbnails(GtkIconView *g, gchar *file) {
  GtkListStore *s;
  GtkTreeIter iter;
  gchar buf[1024];
  const gchar *dirname = g_path_get_dirname(file);

  // get index
  FILE *f = fopen(file, "r");
  if (f == NULL) {
    perror("Error getting index");
    exit(1);
  }

  // create the models
  s = gtk_list_store_new(3, GDK_TYPE_PIXBUF, G_TYPE_STRING, G_TYPE_STRING);
  found_items = gtk_list_store_new(3, GDK_TYPE_PIXBUF, G_TYPE_STRING, G_TYPE_STRING);


  // get all the thumbnails
  while (1) {
    GError *err = NULL;
    gchar *tmp, *tmp2;
    gchar *filename, *filename2;
    GdkPixbuf *pix;

    int result;

    result = fscanf(f, "%1024s", buf);
    if (result == EOF) {
      break;
    } else if (result != 1) {
      perror("bad result");
    }

    tmp = g_strdup_printf("%s.JPG", buf);
    tmp2 = g_strdup_printf("%s.txt", buf);

    filename = g_build_filename(dirname, tmp, NULL);
    filename2 = g_build_filename(dirname, tmp2, NULL);

    pix = gdk_pixbuf_new_from_file_at_size(filename,
					   150,
					   -1,
					   &err);
    if (err != NULL) {
      g_critical("error: %s", err->message);
      g_error_free(err);
    }

    g_free(tmp);
    g_free(tmp2);

    gtk_list_store_append(s, &iter);
    gtk_list_store_set(s, &iter,
		       0, pix,
		       1, filename,
		       2, filename2,
		       -1);


    g_object_unref(pix);
    g_free(filename);
    g_free(filename2);
  }

  // set it up
  gtk_icon_view_set_model(g, GTK_TREE_MODEL(s));
  gtk_icon_view_set_pixbuf_column(g, 0);
  //gtk_icon_view_set_text_column(g, 2);

  fclose(f);
  g_free(dirname);
}


GladeXML *g_xml;

int
main (int argc, char *argv[])
{
  GtkWidget *fatfind;

  gtk_init(&argc,&argv);
  g_xml = glade_xml_new(FATFIND_GLADEDIR "/fatfind.glade",NULL,NULL);
  g_assert(g_xml != NULL);

  if (argc != 2) {
    g_critical("No image index given on command line");
    return;
  }

  glade_xml_signal_autoconnect(g_xml);
  fatfind = glade_xml_get_widget(g_xml,"fatfind");


  // setup the thumbnails
  setup_thumbnails(GTK_ICON_VIEW(glade_xml_get_widget(g_xml,
						      "calibrationImages")),
		   argv[1]);

  // init saved searches
  setup_saved_search_store();

  // initialize Diamond
  init_diamond();


  gtk_widget_show_all(fatfind);

  gtk_main();
  return 0;
}

